Repository AntHurry/AntHurry, pull requests merged in 2023-07, with the labels that each got.

#98 Feature/search writing: 온라인 게시글 검색
  src/main/java/com/ant/hurry/base/home/HomeController.java
  src/main/java/com/ant/hurry/boundedContext/board/controller/BoardController.java
  src/main/java/com/ant/hurry/boundedContext/board/repository/BoardRepository.java
  src/main/java/com/ant/hurry/boundedContext/board/service/BoardService.java
  src/main/resources/templates/board/enterRegion.html
  src/main/resources/templates/board/online.html
  src/main/resources/templates/usr/home/main.html
Labels: enhancement

#96 Feature/connectChat: 채팅 관련 전체 코드 리팩토링 및 TradeStatus-ChatRoom 연결, html 수정
  src/main/java/com/ant/hurry/base/security/SecurityConfig.java
  src/main/java/com/ant/hurry/boundedContext/board/entity/Board.java
  src/main/java/com/ant/hurry/boundedContext/board/repository/BoardRepository.java
  src/main/java/com/ant/hurry/boundedContext/board/service/BoardService.java
  src/main/java/com/ant/hurry/boundedContext/review/service/ReviewService.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/code/TradeStatusErrorCode.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/code/TradeStatusSuccessCode.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusService.java
  src/main/java/com/ant/hurry/chat/baseEntity/BaseMessage.java
  src/main/java/com/ant/hurry/chat/baseEntity/Message.java
  src/main/java/com/ant/hurry/chat/controller/ChatRoomController.java
  src/main/java/com/ant/hurry/chat/entity/ChatFileMessage.java
  src/main/java/com/ant/hurry/chat/entity/ChatMessage.java
  src/main/java/com/ant/hurry/chat/entity/LatestMessage.java
  src/main/java/com/ant/hurry/chat/entity/Message.java
  src/main/java/com/ant/hurry/chat/repository/ChatMessageRepository.java
  src/main/java/com/ant/hurry/chat/repository/CustomChatRoomRepository.java
  src/main/java/com/ant/hurry/chat/service/ChatMessageService.java
  src/main/java/com/ant/hurry/chat/service/ChatRoomService.java
  src/main/java/com/ant/hurry/chat/service/LatestMessageService.java
  src/main/resources/templates/board/board.html
  src/main/resources/templates/chat/room.html
  src/test/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusControllerTest.java
  src/test/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusServiceTest.java
  src/test/java/com/ant/hurry/chat/controller/ChatRoomControllerTest.java
Labels: bug, enhancement

#102 Feature/opponent profile: 멤버의 프로필 확인 페이지 구현
  src/main/java/com/ant/hurry/boundedContext/member/controller/MemberController.java
  src/main/java/com/ant/hurry/boundedContext/member/service/MemberService.java
  src/main/java/com/ant/hurry/boundedContext/review/controller/ReviewController.java
  src/main/java/com/ant/hurry/boundedContext/review/repository/ReviewRepository.java
  src/main/java/com/ant/hurry/boundedContext/review/service/ReviewService.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/repository/TradeStatusRepository.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusService.java
  src/main/resources/templates/review/list.html
  src/main/resources/templates/usr/member/profile.html
  src/main/resources/templates/usr/member/usrCheck.html
  src/test/java/com/ant/hurry/boundedContext/member/controller/MemberControllerTest.java
  src/test/java/com/ant/hurry/boundedContext/member/service/MemberServiceTest.java
  src/test/java/com/ant/hurry/boundedContext/review/service/ReviewServiceTest.java
  src/test/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusServiceTest.java
Labels: enhancement

#103 Feature/chatting: 필요없는 디펜던시 제거, 채팅 관련 리팩토링
  build.gradle
  src/main/java/com/ant/hurry/base/security/SecurityConfig.java
  src/main/java/com/ant/hurry/chat/config/StompWebSocketConfig.java
  src/main/java/com/ant/hurry/chat/controller/ChatMessageController.java
  src/main/java/com/ant/hurry/chat/dto/ChatMessageDto.java
  src/main/java/com/ant/hurry/chat/entity/ChatMessage.java
  src/main/java/com/ant/hurry/chat/service/ChatMessageService.java
  src/main/resources/templates/chat/room.html
  src/test/java/com/ant/hurry/chat/service/ChatMessageServiceTest.java
Labels: enhancement

#115 Feature/chatting: 채팅 페이지에서 메시지가 제대로 나타나도록 구현
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
  src/main/java/com/ant/hurry/chat/baseEntity/BaseMessage.java
  src/main/java/com/ant/hurry/chat/baseEntity/Message.java
  src/main/java/com/ant/hurry/chat/config/MongoConfig.java
  src/main/java/com/ant/hurry/chat/controller/ChatMessageController.java
  src/main/java/com/ant/hurry/chat/controller/ChatRoomController.java
  src/main/java/com/ant/hurry/chat/dto/ChatMessageDto.java
  src/main/java/com/ant/hurry/chat/entity/ChatFileMessage.java
  src/main/java/com/ant/hurry/chat/entity/ChatMessage.java
  src/main/java/com/ant/hurry/chat/entity/ChatRoom.java
  src/main/java/com/ant/hurry/chat/entity/LatestMessage.java
  src/main/java/com/ant/hurry/chat/repository/ChatMessageRepository.java
  src/main/java/com/ant/hurry/chat/repository/CustomChatMessageRepository.java
  src/main/java/com/ant/hurry/chat/repository/CustomChatMessageRepositoryImpl.java
  src/main/java/com/ant/hurry/chat/repository/CustomLatestMessageRepository.java
  src/main/java/com/ant/hurry/chat/repository/CustomLatestMessageRepositoryImpl.java
  src/main/java/com/ant/hurry/chat/repository/LatestMessageRepository.java
  src/main/java/com/ant/hurry/chat/service/ChatMessageService.java
  src/main/java/com/ant/hurry/chat/service/LatestMessageService.java
  src/main/resources/application-prod.yml
  src/main/resources/templates/chat/myRooms.html
  src/main/resources/templates/chat/room.html
  src/test/java/com/ant/hurry/chat/repository/ChatMessageRepositoryTest.java
  src/test/java/com/ant/hurry/chat/service/ChatMessageServiceTest.java
Labels: enhancement

#120 Fix/authority : 권한 분리
  src/main/java/com/ant/hurry/base/initData/DataLoader.java
  src/main/java/com/ant/hurry/boundedContext/adm/controller/AdmController.java
  src/main/java/com/ant/hurry/boundedContext/member/controller/MemberController.java
  src/main/java/com/ant/hurry/boundedContext/member/entity/Member.java
  src/main/java/com/ant/hurry/boundedContext/member/entity/Role.java
  src/main/java/com/ant/hurry/boundedContext/member/entity/RoleType.java
  src/main/java/com/ant/hurry/boundedContext/member/repository/RoleRepository.java
  src/main/java/com/ant/hurry/boundedContext/member/service/MemberService.java
  src/main/resources/data_h2.sql
  src/main/resources/templates/usr/member/profile_edit.html
  src/test/java/com/ant/hurry/boundedContext/member/service/MemberServiceUnitTest.java
Labels: bug

#121 Feature/chatting: 거래 상태 변경, 채팅방 나가기 기능 구현
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusService.java
  src/main/java/com/ant/hurry/chat/controller/ChatMessageController.java
  src/main/java/com/ant/hurry/chat/controller/ChatRoomController.java
  src/main/java/com/ant/hurry/chat/entity/ChatFileMessage.java
  src/main/java/com/ant/hurry/chat/repository/CustomChatRoomRepository.java
  src/main/java/com/ant/hurry/chat/repository/CustomChatRoomRepositoryImpl.java
  src/main/java/com/ant/hurry/chat/service/ChatRoomService.java
  src/main/resources/templates/chat/myRooms.html
  src/main/resources/templates/chat/room.html
  src/test/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusServiceTest.java
  src/test/java/com/ant/hurry/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/ant/hurry/chat/service/ChatMessageServiceTest.java
Labels: enhancement

#131 Feature/sendFile : 채팅방, 채팅 목록 로직 및 html 수정
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
  src/main/java/com/ant/hurry/chat/baseEntity/Message.java
  src/main/java/com/ant/hurry/chat/controller/ChatMessageController.java
  src/main/java/com/ant/hurry/chat/controller/ChatRoomController.java
  src/main/java/com/ant/hurry/chat/entity/ChatFileMessage.java
  src/main/java/com/ant/hurry/chat/entity/ChatMessage.java
  src/main/java/com/ant/hurry/chat/service/ChatMessageService.java
  src/main/resources/templates/chat/myRooms.html
  src/main/resources/templates/chat/room.html
Labels: bug, enhancement

#136 Feature/chatting: 빌드 시 몽고 디비 초기화 및 닉네임 -> 유저네임으로 수정
  src/main/java/com/ant/hurry/base/initData/DataLoader.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
  src/main/java/com/ant/hurry/chat/entity/ChatRoom.java
  src/main/java/com/ant/hurry/chat/entity/LatestMessage.java
  src/main/java/com/ant/hurry/chat/service/ChatMessageService.java
  src/main/java/com/ant/hurry/chat/service/LatestMessageService.java
  src/main/resources/templates/chat/myRooms.html
  src/main/resources/templates/chat/room.html
Labels: enhancement

#140 Feature/chatting: 채팅 메시지로 파일 다운로드 받을 수 있도록 구현 & Jasypt 적용
  build.gradle
  src/main/java/com/ant/hurry/base/jasypt/JasyptConfig.java
  src/main/java/com/ant/hurry/chat/controller/ChatMessageController.java
  src/main/java/com/ant/hurry/chat/controller/ChatRoomController.java
  src/main/java/com/ant/hurry/chat/entity/ChatFileMessage.java
  src/main/java/com/ant/hurry/chat/repository/ChatFileMessageRepository.java
  src/main/java/com/ant/hurry/chat/repository/CustomChatRoomRepository.java
  src/main/java/com/ant/hurry/chat/repository/CustomChatRoomRepositoryImpl.java
  src/main/java/com/ant/hurry/chat/service/ChatMessageService.java
  src/main/java/com/ant/hurry/chat/service/ChatRoomService.java
  src/main/resources/application.yml
  src/main/resources/templates/chat/myRooms.html
  src/main/resources/templates/chat/room.html
  src/test/java/com/ant/hurry/chat/repository/ChatMessageRepositoryTest.java
  src/test/java/com/ant/hurry/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/com/ant/hurry/chat/service/ChatMessageServiceTest.java
  src/test/java/com/ant/hurry/chat/service/ChatRoomServiceTest.java
Labels: enhancement

#145 Feature/chat: 채팅 관련 로직 수정 및 Swagger 적용
  src/main/java/com/ant/hurry/boundedContext/favorite/entity/Favorite.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
  src/main/java/com/ant/hurry/chat/baseEntity/Message.java
  src/main/java/com/ant/hurry/chat/controller/ChatMessageController.java
  src/main/java/com/ant/hurry/chat/controller/ChatRoomController.java
  src/main/java/com/ant/hurry/chat/entity/ChatFileMessage.java
  src/main/java/com/ant/hurry/chat/entity/ChatMessage.java
  src/main/java/com/ant/hurry/chat/entity/LatestMessage.java
  src/main/java/com/ant/hurry/chat/service/ChatMessageService.java
  src/main/java/com/ant/hurry/chat/service/ChatRoomService.java
  src/main/java/com/ant/hurry/chat/service/LatestMessageService.java
  src/main/resources/templates/chat/myRooms.html
  src/main/resources/templates/chat/room.html
Labels: enhancement

#148 Feature/chat: 채팅방 나가기 로직 수정
  src/main/java/com/ant/hurry/chat/code/ChatRoomErrorCode.java
  src/main/java/com/ant/hurry/chat/controller/ChatRoomController.java
  src/main/java/com/ant/hurry/chat/entity/ChatRoom.java
  src/main/java/com/ant/hurry/chat/service/ChatRoomService.java
  src/main/java/com/ant/hurry/chat/service/LatestMessageService.java
  src/main/resources/templates/chat/myRooms.html
Labels: enhancement

#153 Feature/modify : 거래 상태 생성 시 requester, helper 설정 변경
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
Labels: enhancement

#155 feature/point: 코인 거래 기능 구현하였습니다.
  src/main/java/com/ant/hurry/base/region/initData/initRegion.java
  src/main/java/com/ant/hurry/base/security/SecurityConfig.java
  src/main/java/com/ant/hurry/boundedContext/board/service/BoardService.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/event/EventAfterUpdateStatus.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/event/TradeStatusEventListener.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusService.java
  src/main/java/com/ant/hurry/chat/service/ChatRoomService.java
  src/main/resources/static/img/loginpage.png
  src/main/resources/static/img/mainpage.png
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/usr/home/main.html
  src/main/resources/templates/usr/member/login.html
Labels: enhancement

#156 Feature/chat: 알림 메시지가 latestMessage에도 저장되도록 수정
  src/main/java/com/ant/hurry/chat/service/ChatMessageService.java
Labels: enhancement

#163 Fix/chat: 몽고 디비 초기화 로직을 분리
  src/main/java/com/ant/hurry/base/initData/DataLoader.java
  src/main/java/com/ant/hurry/base/initData/InitializeMongoDb.java
  src/main/java/com/ant/hurry/chat/controller/ChatRoomController.java
Labels: enhancement

#166 Fix/tradeStatus: 거래현황 로직 및 기타 수정
  src/main/java/com/ant/hurry/boundedContext/adm/code/AdmErrorCode.java
  src/main/java/com/ant/hurry/boundedContext/adm/code/AdmSuccessCode.java
  src/main/java/com/ant/hurry/boundedContext/coin/code/ExchangeErrorCode.java
  src/main/java/com/ant/hurry/boundedContext/coin/code/ExchangeSuccessCode.java
  src/main/java/com/ant/hurry/boundedContext/member/controller/MemberController.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/code/TradeStatusErrorCode.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/code/TradeStatusSuccessCode.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/repository/TradeStatusRepository.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusService.java
  src/main/java/com/ant/hurry/chat/code/ChatMessageErrorCode.java
  src/main/java/com/ant/hurry/chat/code/ChatMessageSuccessCode.java
  src/main/java/com/ant/hurry/chat/code/ChatRoomErrorCode.java
  src/main/java/com/ant/hurry/chat/code/ChatRoomSuccessCode.java
  src/main/resources/static/img/profile.png
  src/main/resources/templates/chat/room.html
  src/test/java/com/ant/hurry/boundedContext/adm/service/AdmServiceTest.java
  src/test/java/com/ant/hurry/boundedContext/coin/service/CoinServiceTest.java
  src/test/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusServiceTest.java
Labels: enhancement

#168 Feature/afterreview: 알림창에서 helper는 리뷰 작성 할 수 있도록 했습니다.
  src/main/java/com/ant/hurry/boundedContext/notification/entity/Notification.java
  src/main/java/com/ant/hurry/boundedContext/notification/service/NotificationService.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
  src/main/resources/templates/notification/list.html
  src/test/java/com/ant/hurry/boundedContext/notification/service/NotificationServiceTest.java
Labels: enhancement

#173 Fix/chat: 채팅 목록 정렬 및 채팅방에서 상대방 프로필 조회
  src/main/java/com/ant/hurry/chat/controller/ChatRoomController.java
  src/main/resources/templates/chat/room.html
Labels: enhancement

#177 Fix/board and faq: 동네 게시판에서 검색할 때 두 글자 이상 되도록, 검색 내용이 없을 경우, faq
  src/main/java/com/ant/hurry/base/security/SecurityConfig.java
  src/main/java/com/ant/hurry/boundedContext/board/controller/BoardController.java
  src/main/resources/templates/board/enterRegion.html
  src/main/resources/templates/board/online.html
  src/main/resources/templates/board/search.html
  src/main/resources/templates/usr/member/login.html
Labels: enhancement

#178 Fix/chat: 채팅 메시지의 프로필 이미지 클릭 시에도 프로필 조회 가능
  src/main/resources/templates/chat/room.html
Labels: enhancement

#184 Fix/style: 뱃지, 버튼 색상 변경
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/entity/TradeStatus.java
  src/main/resources/templates/board/board.html
  src/main/resources/templates/board/enterRegion.html
Labels: enhancement

#179 Fix/search: 검색 결과 수정, 이모지 알맞게 수정
  src/main/java/com/ant/hurry/boundedContext/board/repository/BoardRepositoryImpl.java
  src/main/resources/templates/board/online.html
  src/main/resources/templates/board/search.html
Labels: enhancement

#183 Feature/myboard: 내 게시글 확인
  src/main/java/com/ant/hurry/boundedContext/board/repository/BoardRepositoryCustom.java
  src/main/java/com/ant/hurry/boundedContext/board/repository/BoardRepositoryImpl.java
  src/main/java/com/ant/hurry/boundedContext/board/service/BoardService.java
  src/main/java/com/ant/hurry/boundedContext/member/controller/MemberController.java
  src/main/resources/templates/usr/member/myboard.html
  src/main/resources/templates/usr/member/profile.html
Labels: enhancement

#188 Fix/chat: 채팅 퇴장 및 재입장 로직 수정, html 일부 수정
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
  src/main/java/com/ant/hurry/chat/code/ChatRoomErrorCode.java
  src/main/java/com/ant/hurry/chat/code/ChatRoomSuccessCode.java
  src/main/java/com/ant/hurry/chat/controller/ChatMessageController.java
  src/main/java/com/ant/hurry/chat/controller/ChatRoomController.java
  src/main/java/com/ant/hurry/chat/service/ChatRoomService.java
  src/main/resources/templates/board/search.html
  src/main/resources/templates/chat/myRooms.html
  src/main/resources/templates/chat/room.html
  src/test/java/com/ant/hurry/chat/service/ChatRoomServiceTest.java
Labels: enhancement

#187 Fix/mobile: 모바일에서 생기는 UI 문제 해결
  src/main/resources/data_h2.sql
  src/main/resources/templates/coin/charge.html
  src/main/resources/templates/usr/home/main.html
  src/main/resources/templates/usr/member/login.html
Labels: enhancement

#190 Fix/notification 채팅 시작 시, SMS
  src/main/java/com/ant/hurry/boundedContext/notification/service/NotificationService.java
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
  src/test/java/com/ant/hurry/boundedContext/notification/service/NotificationServiceTest.java
Labels: bug

#191 Fix/chat: 채팅방 재입장 로직 수정
  src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
Labels: enhancement
